ADMINISTER ANY SQL TUNING SET   
ADMINISTER ANY SQL TUNING SET
ADMINISTER DATABASE TRIGGER
ADMINISTER DATABASE TRIGGER
ADMINISTER RESOURCE MANAGER
ADMINISTER RESOURCE MANAGER
ADMINISTER SQL TUNING SET
ADMINISTER SQL TUNING SET
ADVISOR
ADVISOR
ALTER ANY CLUSTER
ALTER ANY CLUSTER
ALTER ANY DIMENSION
ALTER ANY DIMENSION
ALTER ANY EVALUATION CONTEXT
ALTER ANY EVALUATION CONTEXT
ALTER ANY INDEX
ALTER ANY INDEX
ALTER ANY INDEXTYPE
ALTER ANY INDEXTYPE
ALTER ANY LIBRARY
ALTER ANY LIBRARY
ALTER ANY MATERIALIZED VIEW
ALTER ANY MATERIALIZED VIEW
ALTER ANY OUTLINE
ALTER ANY OUTLINE
ALTER ANY PROCEDURE
ALTER ANY PROCEDURE
ALTER ANY ROLE
ALTER ANY ROLE
ALTER ANY RULE
ALTER ANY RULE
ALTER ANY RULE SET
ALTER ANY RULE SET
ALTER ANY SEQUENCE
ALTER ANY SEQUENCE
ALTER ANY SQL PROFILE
ALTER ANY SQL PROFILE
ALTER ANY TABLE
ALTER ANY TABLE
ALTER ANY TRIGGER
ALTER ANY TRIGGER
ALTER ANY TYPE
ALTER ANY TYPE
ALTER DATABASE
ALTER DATABASE
ALTER PROFILE
ALTER PROFILE
ALTER RESOURCE COST
ALTER RESOURCE COST
ALTER ROLLBACK SEGMENT
ALTER ROLLBACK SEGMENT
ALTER SESSION
ALTER SESSION
ALTER SYSTEM
ALTER SYSTEM
ALTER TABLESPACE
ALTER TABLESPACE
ALTER USER
ALTER USER
ANALYZE ANY
ANALYZE ANY
ANALYZE ANY DICTIONARY
AUDIT ANY
AUDIT ANY
AUDIT SYSTEM
AUDIT SYSTEM
BACKUP ANY TABLE
BACKUP ANY TABLE
BECOME USER
BECOME USER
CHANGE NOTIFICATION
CHANGE NOTIFICATION
COMMENT ANY TABLE
COMMENT ANY TABLE
CREATE ANY CLUSTER
CREATE ANY CLUSTER
CREATE ANY CONTEXT
CREATE ANY CONTEXT
CREATE ANY DIMENSION
CREATE ANY DIMENSION
CREATE ANY DIRECTORY
CREATE ANY DIRECTORY
CREATE ANY EVALUATION CONTEXT
CREATE ANY EVALUATION CONTEXT
CREATE ANY INDEX
CREATE ANY INDEX
CREATE ANY INDEXTYPE
CREATE ANY INDEXTYPE
CREATE ANY JOB
CREATE ANY JOB
CREATE ANY LIBRARY
CREATE ANY LIBRARY
CREATE ANY MATERIALIZED VIEW
CREATE ANY MATERIALIZED VIEW
CREATE ANY OPERATOR
CREATE ANY OPERATOR
CREATE ANY OUTLINE
CREATE ANY OUTLINE
CREATE ANY PROCEDURE
CREATE ANY PROCEDURE
CREATE ANY RULE
CREATE ANY RULE
CREATE ANY RULE SET
CREATE ANY RULE SET
CREATE ANY SEQUENCE
CREATE ANY SEQUENCE
CREATE ANY SQL PROFILE
CREATE ANY SQL PROFILE
CREATE ANY SYNONYM
CREATE ANY SYNONYM
CREATE ANY TABLE
CREATE ANY TABLE
CREATE ANY TRIGGER
CREATE ANY TRIGGER
CREATE ANY TYPE
CREATE ANY TYPE
CREATE ANY VIEW
CREATE ANY VIEW
CREATE CLUSTER
CREATE CLUSTER
CREATE CLUSTER
CREATE DATABASE LINK
CREATE DATABASE LINK
CREATE DIMENSION
CREATE DIMENSION
CREATE EVALUATION CONTEXT
CREATE EVALUATION CONTEXT
CREATE EXTERNAL JOB
CREATE EXTERNAL JOB
CREATE INDEXTYPE
CREATE INDEXTYPE
CREATE INDEXTYPE
CREATE JOB
CREATE JOB
CREATE LIBRARY
CREATE LIBRARY
CREATE MATERIALIZED VIEW
CREATE MATERIALIZED VIEW
CREATE OPERATOR
CREATE OPERATOR
CREATE OPERATOR
CREATE PROCEDURE
CREATE PROCEDURE
CREATE PROCEDURE
CREATE PROFILE
CREATE PROFILE
CREATE PUBLIC DATABASE LINK
CREATE PUBLIC DATABASE LINK
CREATE PUBLIC SYNONYM
CREATE PUBLIC SYNONYM
CREATE ROLE
CREATE ROLE
CREATE ROLLBACK SEGMENT
CREATE ROLLBACK SEGMENT
CREATE RULE
CREATE RULE
CREATE RULE SET
CREATE RULE SET
CREATE SEQUENCE
CREATE SEQUENCE
CREATE SEQUENCE
CREATE SESSION
CREATE SESSION
CREATE SESSION
CREATE SYNONYM
CREATE SYNONYM
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLESPACE
CREATE TABLESPACE
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TYPE
CREATE TYPE
CREATE TYPE
CREATE USER
CREATE USER
CREATE VIEW
CREATE VIEW
DEBUG ANY PROCEDURE
DEBUG ANY PROCEDURE
DEBUG CONNECT SESSION
DEBUG CONNECT SESSION
DELETE ANY TABLE
DELETE ANY TABLE
DEQUEUE ANY QUEUE
DEQUEUE ANY QUEUE
DROP ANY CLUSTER
DROP ANY CLUSTER
DROP ANY CONTEXT
DROP ANY CONTEXT
DROP ANY DIMENSION
DROP ANY DIMENSION
DROP ANY DIRECTORY
DROP ANY DIRECTORY
DROP ANY EVALUATION CONTEXT
DROP ANY EVALUATION CONTEXT
DROP ANY INDEX
DROP ANY INDEX
DROP ANY INDEXTYPE
DROP ANY INDEXTYPE
DROP ANY LIBRARY
DROP ANY LIBRARY
DROP ANY MATERIALIZED VIEW
DROP ANY MATERIALIZED VIEW
DROP ANY OPERATOR
DROP ANY OPERATOR
DROP ANY OUTLINE
DROP ANY OUTLINE
DROP ANY PROCEDURE
DROP ANY PROCEDURE
DROP ANY ROLE
DROP ANY ROLE
DROP ANY RULE
DROP ANY RULE
DROP ANY RULE SET
DROP ANY RULE SET
DROP ANY SEQUENCE
DROP ANY SEQUENCE
DROP ANY SQL PROFILE
DROP ANY SQL PROFILE
DROP ANY SYNONYM
DROP ANY SYNONYM
DROP ANY TABLE
DROP ANY TABLE
DROP ANY TRIGGER
DROP ANY TRIGGER
DROP ANY TYPE
DROP ANY TYPE
DROP ANY VIEW
DROP ANY VIEW
DROP PROFILE
DROP PROFILE
DROP PUBLIC DATABASE LINK
DROP PUBLIC DATABASE LINK
DROP PUBLIC SYNONYM
DROP PUBLIC SYNONYM
DROP ROLLBACK SEGMENT
DROP ROLLBACK SEGMENT
DROP TABLESPACE
DROP TABLESPACE
DROP USER
DROP USER
ENQUEUE ANY QUEUE
ENQUEUE ANY QUEUE
EXECUTE ANY CLASS
EXECUTE ANY CLASS
EXECUTE ANY EVALUATION CONTEXT
EXECUTE ANY EVALUATION CONTEXT
EXECUTE ANY INDEXTYPE
EXECUTE ANY INDEXTYPE
EXECUTE ANY LIBRARY
EXECUTE ANY LIBRARY
EXECUTE ANY OPERATOR
EXECUTE ANY OPERATOR
EXECUTE ANY PROCEDURE
EXECUTE ANY PROCEDURE
EXECUTE ANY PROGRAM
EXECUTE ANY PROGRAM
EXECUTE ANY RULE
EXECUTE ANY RULE
EXECUTE ANY RULE SET
EXECUTE ANY RULE SET
EXECUTE ANY TYPE
EXECUTE ANY TYPE
EXPORT FULL DATABASE
EXPORT FULL DATABASE
FLASHBACK ANY TABLE
FLASHBACK ANY TABLE
FORCE ANY TRANSACTION
FORCE ANY TRANSACTION
FORCE TRANSACTION
FORCE TRANSACTION
GLOBAL QUERY REWRITE
GLOBAL QUERY REWRITE
GRANT ANY OBJECT PRIVILEGE
GRANT ANY OBJECT PRIVILEGE
GRANT ANY PRIVILEGE
GRANT ANY PRIVILEGE
GRANT ANY ROLE
GRANT ANY ROLE
IMPORT FULL DATABASE
IMPORT FULL DATABASE
INSERT ANY TABLE
INSERT ANY TABLE
LOCK ANY TABLE
LOCK ANY TABLE
MANAGE ANY FILE GROUP
MANAGE ANY FILE GROUP
MANAGE ANY QUEUE
MANAGE ANY QUEUE
MANAGE FILE GROUP
MANAGE FILE GROUP
MANAGE SCHEDULER
MANAGE SCHEDULER
MANAGE TABLESPACE
MANAGE TABLESPACE
MERGE ANY VIEW
MERGE ANY VIEW
ON COMMIT REFRESH
ON COMMIT REFRESH
QUERY REWRITE
QUERY REWRITE
READ ANY FILE GROUP
READ ANY FILE GROUP
RESTRICTED SESSION
RESTRICTED SESSION
RESUMABLE
RESUMABLE
SELECT ANY DICTIONARY
SELECT ANY SEQUENCE
SELECT ANY SEQUENCE
SELECT ANY TABLE
SELECT ANY TABLE
SELECT ANY TRANSACTION
SELECT ANY TRANSACTION
UNDER ANY TABLE
UNDER ANY TABLE
UNDER ANY TYPE
UNDER ANY TYPE
UNDER ANY VIEW
UNDER ANY VIEW
UNLIMITED TABLESPACE
UPDATE ANY TABLE
UPDATE ANY TABLE