package net.vpc.dbclient.plugin.tool.importexport.exporter.xml;

import net.vpc.dbclient.plugin.tool.importexport.exporter.fix.FixAlign;

import javax.swing.*;
import java.awt.*;
import java.nio.charset.Charset;

/**
 * @author Taha BEN SALAH (taha.bensalah@gmail.com)  alias vpc
 * @creationtime 2009/08/07 19:55:55
 */
public class ExportDataXmlForm {
    private JPanel mainPanel;
    private JLabel encodingLabel;
    private JComboBox encodingComboBox;
    private JCheckBox openFileWhenFinishedCheckBox;
    private JLabel documentElementLabel;
    private JLabel rowElementLabel;
    private JTable columnsTable;
    private JTextField documentElementText;
    private JTextField rowElementText;

    public ExportDataXmlForm() {
//        ExportConfigXml data = new ExportConfigXml();
//        data.validate();

        getDocumentElementText().setText("Document");
        getRowElementText().setText("Row");

        JComboBox comboBox = new JComboBox();
        comboBox.addItem(FixAlign.LEFT);
        comboBox.addItem(FixAlign.CENTER);
        comboBox.addItem(FixAlign.RIGTH);
        encodingComboBox.addItem(null);
        for (String s : Charset.availableCharsets().keySet()) {
            encodingComboBox.addItem(s);
        }
        encodingComboBox.setSelectedItem(null);
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JLabel getEncodingLabel() {
        return encodingLabel;
    }

    public JComboBox getEncodingComboBox() {
        return encodingComboBox;
    }

    public JCheckBox getOpenFileWhenFinishedCheckBox() {
        return openFileWhenFinishedCheckBox;
    }

    public JLabel getDocumentElementLabel() {
        return documentElementLabel;
    }

    public JLabel getRowElementLabel() {
        return rowElementLabel;
    }

    public JTable getColumnsTable() {
        return columnsTable;
    }

    public JTextField getDocumentElementText() {
        return documentElementText;
    }

    public JTextField getRowElementText() {
        return rowElementText;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        encodingLabel = new JLabel();
        encodingLabel.setText("Encoding");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(encodingLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer2, gbc);
        encodingComboBox = new JComboBox();
        encodingComboBox.setEditable(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(encodingComboBox, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer3, gbc);
        openFileWhenFinishedCheckBox = new JCheckBox();
        openFileWhenFinishedCheckBox.setText("Open File when finished");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(openFileWhenFinishedCheckBox, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer8, gbc);
        documentElementLabel = new JLabel();
        documentElementLabel.setText("Document Element");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(documentElementLabel, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer9, gbc);
        rowElementLabel = new JLabel();
        rowElementLabel.setText("Row Element");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(rowElementLabel, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(454, 200));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane1, gbc);
        columnsTable = new JTable();
        scrollPane1.setViewportView(columnsTable);
        documentElementText = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(documentElementText, gbc);
        rowElementText = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(rowElementText, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer11, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}