name=Violet

menuSelectedBackground=@primary3
controlTextFont=Verdana, PLAIN, 10
menuTextFont=Verdana, PLAIN, 10
focusColor=@secondary2
highlightedTextColor=@white
menuItemSelectedBackground=@textHighlightColor
menuItemSelectedForeground=@white
menuSelectedBackground=@secondary2
textHighlightColor=@primary1


black=57,41,64
white=253,255,255
primary3=231,213,249
secondary3=243,241,247
primary2=182,153,204
secondary2=228,224,238
primary1=130,97,153
secondary1=156,151,191
