Select
v.VIEWDEFINITION VIEW_DEFINITION,
'' as CATALOG_NAME,
s.SCHEMANAME SCHEMA_NAME,
t.TABLENAME VIEW_NAME
From SYS.SYSVIEWS v
inner join SYS.SYSTABLES t on t.TABLEID =v.TABLEID
inner join SYS.SYSSCHEMAS s on s.SCHEMAID = t.SCHEMAID
where
  s.SCHEMANAME Like ${schema?}
  and t.TABLENAME Like ${view?}
