*
TO UNIQUE USING
AS, SELECT, FROM, WHERE, AND, OR, NOT, IN, LIKE, IS, SET, INNER, OUTER,
FULL, OUTER, JOIN, ON, ORDER, BY, DESC, ASC, UPDATE, DELETE, INSERT,
INTO, VALUES, CREATE, TABLE, VIEW, DATABASE,DISTINCT,
DROP, DEFAULT, CONSTRAINT, ADD, ALTER, EXISTS,
END, TRIGGER, ORDER, NULL, PRIMARY, KEY, GROUP, UNION,
FOREIGN, PROCEDURE, FUNCTION, HAVING, REFERENCES, LEFT, RIGHT, OUTER, INNER,
IN, AND, OR, NOT, IS
