package net.vpc.dbclient.plugin.tool.importexport.exporter.fix;

import javax.swing.*;
import java.awt.*;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.Map;

/**
 * @author Taha BEN SALAH (taha.bensalah@gmail.com)  alias vpc
 * @creationtime 2009/08/07 19:55:55
 */
public class ExportDataFixForm {
    private JPanel mainPanel;
    private JLabel encodingLabel;
    private JComboBox encodingComboBox;
    private JCheckBox exportHeadersCheckBox;
    private JCheckBox openFileWhenFinishedCheckBox;
    private JComboBox lineSeparatorComboBox;
    private JLabel lineSeparatorLabel;
    private JComboBox fieldSeparatorComboBox;
    private JLabel fieldSeparatorLabel;
    private JTable columnsTable;
    private static final String SEP_R = "MacOs (\\r)";
    private static final String SEP_RN = "DOS/Windows (\\r\\n)";
    private static final String SEP_N = "Unix/Linux (\\n)";
    private static final String SEP_TAB = "TAB (\\t)";
    public final static Map<String, String> encodedStrings = new HashMap<String, String>();

    static {
        encodedStrings.put(SEP_R, "\r");
        encodedStrings.put(SEP_RN, "\r\n");
        encodedStrings.put(SEP_N, "\n");
        encodedStrings.put(SEP_TAB, "\t");
    }

    public ExportDataFixForm() {
        ExportConfigFix data = new ExportConfigFix();
        data.validate();

        //form.getContentCoteComboBox().setModel(new DefaultComboBoxModel(new Object[]{"\"", "\'", ""}));
        //form.getContentCoteComboBox().setSelectedItem(data.getContentCotes());

        getLineSeparatorComboBox().setModel(new DefaultComboBoxModel(new Object[]{SEP_R, SEP_RN, SEP_N}));
        getLineSeparatorComboBox().setSelectedItem(null);

        getFieldSeparatorComboBox().setModel(new DefaultComboBoxModel(new Object[]{",", ";", ":", "$", "|", SEP_TAB}));
        getFieldSeparatorComboBox().setSelectedItem(data.getFieldSeparator());
        //form.getCoteAlwaysCheckBox().setSelected(data.isCoteAlways());
        getOpenFileWhenFinishedCheckBox().setSelected(data.isOpenFile());
        getExportHeadersCheckBox().setSelected(data.isExportHeaders());
        encodingComboBox.addItem(null);
        for (String s : Charset.availableCharsets().keySet()) {
            encodingComboBox.addItem(s);
        }
        encodingComboBox.setSelectedItem(null);

    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JLabel getEncodingLabel() {
        return encodingLabel;
    }

    public JComboBox getEncodingComboBox() {
        return encodingComboBox;
    }

    public JCheckBox getExportHeadersCheckBox() {
        return exportHeadersCheckBox;
    }

    public JCheckBox getOpenFileWhenFinishedCheckBox() {
        return openFileWhenFinishedCheckBox;
    }

    public JComboBox getLineSeparatorComboBox() {
        return lineSeparatorComboBox;
    }

    public JLabel getLineSeparatorLabel() {
        return lineSeparatorLabel;
    }

    public JComboBox getFieldSeparatorComboBox() {
        return fieldSeparatorComboBox;
    }

    public JLabel getFieldSeparatorLabel() {
        return fieldSeparatorLabel;
    }

    public JTable getColumnsTable() {
        return columnsTable;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        encodingLabel = new JLabel();
        encodingLabel.setText("Encoding");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(encodingLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer2, gbc);
        encodingComboBox = new JComboBox();
        encodingComboBox.setEditable(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(encodingComboBox, gbc);
        exportHeadersCheckBox = new JCheckBox();
        exportHeadersCheckBox.setText("Export Headers");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(exportHeadersCheckBox, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer3, gbc);
        openFileWhenFinishedCheckBox = new JCheckBox();
        openFileWhenFinishedCheckBox.setText("Open File when finished");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(openFileWhenFinishedCheckBox, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer10, gbc);
        lineSeparatorLabel = new JLabel();
        lineSeparatorLabel.setText("Line Separator");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(lineSeparatorLabel, gbc);
        lineSeparatorComboBox = new JComboBox();
        lineSeparatorComboBox.setEditable(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(lineSeparatorComboBox, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer11, gbc);
        fieldSeparatorLabel = new JLabel();
        fieldSeparatorLabel.setText("Field Separator");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(fieldSeparatorLabel, gbc);
        fieldSeparatorComboBox = new JComboBox();
        fieldSeparatorComboBox.setEditable(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(fieldSeparatorComboBox, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(454, 200));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane1, gbc);
        columnsTable = new JTable();
        scrollPane1.setViewportView(columnsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
